# Generated by Django 3.1.7 on 2021-02-19 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0005_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='company_rul',
            new_name='company_url',
        ),
    ]
